Added Romberg's method
dextorious/NumericalIntegration.jl pull request #14
Opened 2018-09-05 12:25 UTC by bernatguillen

I added Romberg's method. It works (not sure if it's very fast). I am working on the fast version with fewer checks and assertions. 

The reason I only start checking for accuracy after 1/3 of the steps have been taken is to avoid situations where the function is 0 almost everywhere and therefore the first few steps all give 0. Other than that the code is almost copying and pasting the wikipedia pseudocode (except indexes starting at 1).

2018-09-10 13:21 UTC, dextorious requested changes
Sorry for the late review. I noted the two reasons the StaticArrays tests fail right now. Fix those when you get a chance and let me know if you intend to add anything further to the PR before you want me to merge it.

2018-09-10 13:21 UTC, dextorious commented on src/NumericalIntegration.jl
> +    rombaux = zeros(typeof(x[1]), maxsteps, 2)
This line is the reason the StaticArrays tests fail, you can't assign a SVector to a Float64. There might be edge cases I'm not considering, but my first impulse would be to write `rombaux = zeros(eltype(y), maxsteps, 2)` there.

2018-09-10 13:21 UTC, dextorious commented on src/NumericalIntegration.jl
> +        if i > maxsteps//3 && abs(rombaux[i, prevrow] - rombaux[i+1, currrow]) < m.acc
This will also fail for StaticArrays due to the `abs` call. Not sure on the exact error metric you want to use here (L2 or Linf?), but replacing `abs` with `norm` will make the tests pass. You can replace it with an infinity norm if you like, the point is it has to be able to deal with SVectors too.

2018-09-14 19:31 UTC, bernatguillen commented on src/NumericalIntegration.jl
> +    rombaux = zeros(typeof(x[1]), maxsteps, 2)
Made the changes you suggested and now tests pass! Thank you very much :1st_place_medal:

2018-09-14 19:57 UTC, bernatguillen commented
I don't plan to add a fast version, for now, I'm not sure how well fastmath would work with some of the operations (TBH not very familiar with fastmath).

2018-09-14 20:40 UTC, bernatguillen commented
Last thing, added a warning at the end in case the extrapolation estimated accuracy isn't below the desired accuracy. It doesn't throw an exception but it is useful for logging. I also added a test to make sure the warning is properly raised.

2018-09-18 15:52 UTC, dextorious commented
All right, looks good to me.

2018-09-18 15:52 UTC, merged